title: "Bundetsag"
description: ""
url: https://bundetsag.de
markdown: kramdown
exclude:
  - "vendor"
  - "CNAME"
  - "Gemfile*"
  - "mission"
  - "README.md"
  - "*.sh"
  - "doc/"
  - "local/"
  - "update_avatars.py"

sass:
    style: :compressed
permalink: /blog/:title
excerpt_separator: "\n"
paginate: 5
paginate_path: "blog/:num"
gems:
  - jekyll-sitemap
  - jekyll-paginate
